# Generated by Django 4.0.6 on 2022-07-27 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Type Of  Incident',
                'verbose_name_plural': 'Type Of Incidents',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('photo', models.FileField(upload_to='photo/incident')),
                ('feedback_reply', models.TextField()),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('date_of_incident', models.DateTimeField()),
                ('type_of_incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.typeofincident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
            },
        ),
    ]
