# Generated by Django 4.0.6 on 2022-07-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_profile_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pics',
            field=models.FileField(default='default.png', upload_to='profile/pics'),
        ),
    ]
